import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <h1 className="bg-red-800">Heloowww dari root layout</h1>
      <Header /> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
